# Generated by Django 6.0.3 on 2026-03-13 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('first_name', models.CharField(max_length=100, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=100, verbose_name='Họ')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='CMND/CCCD')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Ảnh')),
                ('position', models.CharField(max_length=200, verbose_name='Chức vụ')),
                ('hire_date', models.DateField(verbose_name='Ngày vào làm')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày nghỉ việc')),
                ('status', models.CharField(choices=[('active', 'Đang làm việc'), ('inactive', 'Đã nghỉ việc'), ('probation', 'Thử việc')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('basic_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương cơ bản')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department', verbose_name='Phòng ban')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
