# Generated by Django 6.0.3 on 2026-03-13 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Loại nghỉ phép')),
                ('annual_days', models.PositiveIntegerField(default=0, verbose_name='Số ngày phép/năm')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Nghỉ có lương')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Loại nghỉ phép',
                'verbose_name_plural': 'Loại nghỉ phép',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='employees.employee', verbose_name='Người duyệt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Nhân viên')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaves.leavetype', verbose_name='Loại nghỉ phép')),
            ],
            options={
                'verbose_name': 'Đơn xin nghỉ phép',
                'verbose_name_plural': 'Đơn xin nghỉ phép',
                'ordering': ['-created_at'],
            },
        ),
    ]
